MOONSHOT-Team/MOONSHOT-CLIENT

- README.md
- Resolved: #19
- 내용만 가볍게 보세용
보기 편하라고 pr에 미리보기 남겨드립니당
<h1> 🌜 MOONSHOT 🌛 </h1>
<h3> 👩🏻‍🚀 서비스 이름 및 소개 </h3>
```
유난한 도전을 꿈꾸는 당신을 위한 프레임워크, Moonshot
ㄴ moonshot thinking을 바탕으로 목표를 설정하는 이들
ㄴ objective를 설정하는 google의 기업 정신으로, 10%의 개선 보다는 10배의 혁신에 도전한다는 뜻
```
<br/>
<hr/>
<h2>🧑‍💻 MOONSHOT Web Developers </h2>
<br/>
<div align="center">
<table>
<th>팀원</th>
<th> 조연서 <a href="https://github.com/Yeonseo-Jo"><img src="https://img.shields.io/badge/Github-181717?style=flat-square&logo=Github&logoColor=white"/><a></th>
<th> 신수연 <a href="https://github.com/SooY2"><img src="https://img.shields.io/badge/Github-181717?style=flat-square&logo=Github&logoColor=white"/></a></th>
<th> 전언석 <a href="https://github.com/eonseok-jeon"><img src="https://img.shields.io/badge/Github-181717?style=flat-square&logo=Github&logo …
> [Project-docs] 리드미 1차 수정

- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewKrNodes.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewTaskNodes.tsx
- src/PreviewOkr/index.tsx
- src/Router.tsx
- src/common/components/OkrTree/Lines/NodeLines.tsx
- src/common/components/OkrTree/Lines/StraightLine.tsx
- src/common/components/OkrTree/Nodes/CommonOkrNodes.tsx
- src/common/components/OkrTree/Template/KrTemplate/KrContainer.tsx
- src/common/components/OkrTree/Template/KrTemplate/KrTaskContainer.tsx
- src/common/components/OkrTree/Template/OkrTreeTemplate.tsx
- src/common/constants/MOCK_OKR_DATA.ts
- src/common/styles/OkrTree/CommonNodeStyle.tsx
- src/common/type/OkrTree/KeyResultTypes.ts
- src/common/type/OkrTree/TasksTypes.ts
> develop -> feat/common : 트리 그래프 머지

- src/PreviewOkr/components/PreviewModal.tsx
- src/common/components/Modal/index.tsx
- src/common/styles/theme.ts
> [previewOKR] preview okr modal UI 및 기능 구현

- src/Auth/AuthGoogle.tsx
- src/Auth/AuthKakao.tsx
- src/Auth/apis/fetcher.ts
- src/Auth/type/index.ts
- src/NickName/apis/fetcher.ts
- src/NickName/index.tsx
- src/Router.tsx
- src/common/apis/instance.ts
- close #112 
- 수정할 부분이 있을까요?
1. 기본
기본형
```typescript
const { data, error, isLoading } = useSWR<DataType, Error>(url, fetcher);
```
실제 사용 예시
```typescript
export const getUserInfo = async (url: string) => {
const response = await instance.get(url);
return response;
};
```
fetcher 함수 하나 만들고,
컴포넌트 내에서
```typescript
const { data } = useSWR('/v1/user/mypage', getUserInfo);
```
불러 줍니다. 
url가 fetcher의 parameter로 넘어감
`
주의사항 : useSWR은 hook이기에 component 최상단에서만 사용 가능합니다!
`
2. 변수 전달
기본형
```typescript
const { data, error, isLoading } = useSWR<DataType, Error>(
url,
(url: string) => fetcher(url, argu1, argu2, ...),
);
```
실제 사용 예시
```typescript
import axios from 'axios';
export const fetcherPost = async (url: string, code: string, platform: string) => {
const response = await axios.post(
url,
{ …
```
> [signIn] nickname 로직 구현

- src/MainDashBoard/components/drawer/DrawerModal.tsx
- src/MainDashBoard/utils/validateDate.ts
- src/common/components/Modal/index.tsx
- src/common/styles/globalStyles.ts
- src/common/styles/theme.ts
- close #75 
```typescript
<div css={buttonStyle}>
{!activeExtend && (
<>
<StCompleteButton
type="button"
onClick={() => {
// 해당 목표 히스토리로 이동시키기 + /history로 페이지 이동
}}
>
목표 완료하기
</StCompleteButton>
<StExtendButton
type="button"
onClick={() => {
setActiveExtend(true);
}}
>
기간 연장하기
</StExtendButton>
</>
)}
{activeExtend && (
<>
<StCompleteButton
type="button"
onClick={() => {
modalRef.current?.close();
setActiveExtend(false);
}}
>
취소하기
</StCompleteButton>
<StExtendButton type="submit" disabled={!isSave}>
저장하기
</StExtendButton>
</>
)}
</div>
```
이 부분을 어떻게 하면 더 깔끔하게 짤 수 있을까요??
너무 너저분 하네요
index.html에
```html
<div id="modal"></div>
```
추가해 주시고,
common > hooks에
```typescript
import { useRef } from 'react';
/**
* 사용법 :
* 원하는 component 내에서
* const { modalRef, handleShowModal } = useModal();
* 받아온 후, …
```
> [modal] drawer modal UI 및 기능 구현

- src/AddOkr/components/addKr/GuideFirstKeyResultCard.tsx
- src/AddOkr/components/addKr/GuideSecondKeyResultCard.tsx
- src/AddOkr/components/addKr/KeyResultCard.tsx
- src/AddOkr/components/stepLayout/ObjContent.tsx
- src/AddOkr/components/stepLayout/ObjTitleCateg.tsx
- src/AddOkr/index.tsx
- src/AddOkr/types/FinalKrListInfo.ts
- src/AddOkr/types/TaskInfoTypes.ts
- src/PreviewOkr/components/PreviewModal.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewKrNodes.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewObjNode.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewTaskNodes.tsx
- src/PreviewOkr/index.tsx
- src/common/components/Modal/index.tsx
- src/common/components/input/DynamicInput.tsx
> [AddOkr] addOkr -> previewOkr 플로우 연결

- src/MainDashBoard/components/celebrateMotion/CelebrateMotion.tsx
- src/MainDashBoard/components/drawer/DrawerModal.tsx
- src/MainDashBoard/components/mainDashBoardDrawer/GoalItem.tsx
- src/MainDashBoard/components/mainDashBoardDrawer/MainDashBoardDrawer.tsx
- src/MainDashBoard/components/sideSheet/SideSheet.tsx
- src/MainDashBoard/components/sideSheet/krCheckIn/KrCheckIn.tsx
- src/MainDashBoard/components/sideSheet/krCheckIn/KrCheckInInputs.tsx
- src/MainDashBoard/index.tsx
* feat: 선택에서 목표카드 눌렀을 때 트리 나오게
* feat: 목표 달성 시 축하 모션 연결
* feat: 목표 달성 모달
- close #이슈번호
> Main dashboard/#139/flow (#149)

- src/common/components/Layout/Header/index.tsx
> fix: 헤더 z-index 수정

- src/History/components/HistoryProgressBar/index.tsx
- src/History/components/dropDown/HistoryList.tsx
> [QA] history 수정 

- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashTaskNodes.tsx
> feat: kr길이 수정

- src/History/components/HistoryDrawer.tsx
- src/History/components/YearButton.tsx
- src/History/index.tsx
> [history] 수정사항 추가

- src/My/apis/fetcher.ts
- src/My/index.tsx
- yarn.lock
> [My] api 추가 설정

- index.html
- package.json
- src/App.tsx
- yarn.lock
> [project] GA script 추가

- src/common/apis/getNewAccessToken.ts
- src/common/apis/instance.ts
related to: #197
- close #197 
개선될 부분이 있을까요?
[medium 참고자료](https://rathoreaparna678.medium.com/the-ultimate-guide-for-implementing-refresh-token-with-axios-509f8e04f47b)
[블로그 참고자료](https://chorydev.tistory.com/18)
> [signIn] refresh token 로직 구현

- src/AddOkr/components/stepLayout/ObjContent.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewKrNodes.tsx
- src/PreviewOkr/components/PreviewOkrTreeNodes/PreviewObjNode.tsx
- src/common/components/input/DynamicInput.tsx
> [sp1/refactor -> develop] 배포 환경 확인겸 dynamic input 관련 이슈 해결

- src/AddOkr/components/addKr/KeyResultPeriodInput.tsx
- src/MainDashBoard/apis/fetcher.ts
- src/MainDashBoard/components/editModeModal/AddKrModal.tsx
- src/MainDashBoard/components/editOkrTree/EditKrNodes.tsx
- src/MainDashBoard/components/editOkrTree/EditObjectNode.tsx
- src/MainDashBoard/components/editOkrTree/EditTaskNodes.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashObjectNode.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
- src/MainDashBoard/index.tsx
- src/MainDashBoard/type/addKrType.ts
- src/common/components/addKr/AddKrForm.tsx
> [SP1/feat] KR-Task 추가 삭제 api 모달 연결

- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
- close #248 
- krList를 읽을 수 없어서 옵쳐서체이닝으로 처리해주었습니다.
> [fix] obj없을 때 에러 해결

- src/AddOkr/components/addKr/GuideFirstKeyResultCard.tsx
- src/AddOkr/components/addKr/GuideSecondKeyResultCard.tsx
- src/AddOkr/components/addKr/KeyResultCard.tsx
- src/AddOkr/constants/OKR_MAX_LENGTH.ts
- src/MainDashBoard/components/editModeModal/AddKrModal.tsx
- src/common/components/addKr/AddKrForm.tsx
- src/common/constants/addKr/KR_ERR_MSG.ts
- src/common/styles/addKr/CommonErrMsgBoxStyle.tsx
- src/common/utils/addKr/validMaxKrInputVal.ts
> Sp1/feat - > develop (kr 에러 메시지 구현 반영)

- src/AddOkr/components/addKr/KeyResultPeriodInput.tsx
- src/MainDashBoard/components/editModeModal/AddKrModal.tsx
- src/common/components/Modal/index.tsx
> [Sp1/refactor -> develop] : kr 추가 모달 datepicker 팝업 달력 이슈 해결

- .eslintrc.cjs
- src/MainDashBoard/apis/fetcher.ts
- src/MainDashBoard/components/editOkrTree/EditKrNodes.tsx
- src/MainDashBoard/components/editOkrTree/EditObjectNode.tsx
- src/MainDashBoard/components/editOkrTree/EditTaskNodes.tsx
- src/MainDashBoard/components/mainDashBoardDrawer/GoalItem.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/EditBtn.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashKrNodes.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashObjectNode.tsx
- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
- src/MainDashBoard/components/sideSheet/SideSheet.tsx
- src/MainDashBoard/components/sideSheet/krCheckIn/KrCheckInInputs.tsx
- src/MainDashBoard/constants/OKRTREEVIEWS.ts
- src/MainDashBoard/constants/mainDashConstants.ts
- src/MainDashBoard/index.tsx
- src/MainDashBoard/styles/mainDashOKRTreeStyles.ts
- src/common/components/input/DynamicInput.tsx
- src/common/components/okrTree/template/krTemplate/KrContainer.tsx
Reverts MOONSHOT-Team/MOONSHOT-CLIENT#266
> Revert "develop <- SP1/refactor"

- src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
> fix: confilcts 해결

- src/common/components/Error/index.tsx
> fix: error페이지에 헤더 없애기

- src/Onboarding/components/layout/OnboardingFooter.tsx
> fix: url 경로 수정

- src/Onboarding/components/frame/Frame1.tsx
- src/Onboarding/components/layout/OnboardingHeader.tsx
> [Chore] 랜딩 페이지 워딩 수정

- src/Onboarding/components/frame/Frame1.tsx
- src/Onboarding/components/layout/OnboardingHeader.tsx
- src/Onboarding/constants/APPLY_LINK.ts
> [Fix] 랜딩 페이지 워딩 수정 및 링크 변경
